In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [3]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range("20130101", periods=6)

In [5]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))

In [27]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [18]:
df2 = pd.DataFrame({"A":1,
                    "B":pd.Timestamp("20130102"), 
                    "C":pd.Series(1, index=list(range(4)), dtype="float32"), 
                    "D":np.array([3]*4, dtype="int32"),
                    "E":pd.Categorical(["test", "train", "test", "train"]),
                    "F":"foo"})

In [19]:
df2

A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  train  foo
2  1 2013-01-02  1.0  3   test  foo
3  1 2013-01-02  1.0  3  train  foo

In [20]:
df2.dtypes

A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [29]:
df.head()

A         B         C         D
2013-01-01 -1.446105  1.877875  1.148657 -0.676480
2013-01-02 -0.192691  0.860153 -0.212003  0.522061
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488
2013-01-04  0.082516  0.946347  0.740100 -0.963258
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215

In [30]:
df.tail(3)

A         B         C         D
2013-01-04  0.082516  0.946347  0.740100 -0.963258
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215
2013-01-06 -0.120434  1.666412  0.771898 -1.031010

In [31]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [33]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [34]:
df.to_numpy()

array([[-1.44610518,  1.87787465,  1.14865655, -0.67647981],
       [-0.19269131,  0.86015345, -0.21200286,  0.52206141],
       [-0.20411673, -0.28003094, -1.46483344,  1.04748822],
       [ 0.08251615,  0.9463472 ,  0.74010035, -0.96325835],
       [ 0.860888  , -0.88409616, -1.0290834 , -1.50521493],
       [-0.1204341 ,  1.66641241,  0.77189848, -1.03100976]])

In [35]:
import torch

In [38]:
torch.from_numpy(df.to_numpy())

tensor([[-1.4461,  1.8779,  1.1487, -0.6765],
        [-0.1927,  0.8602, -0.2120,  0.5221],
        [-0.2041, -0.2800, -1.4648,  1.0475],
        [ 0.0825,  0.9463,  0.7401, -0.9633],
        [ 0.8609, -0.8841, -1.0291, -1.5052],
        [-0.1204,  1.6664,  0.7719, -1.0310]], dtype=torch.float64)

In [39]:
df2.to_numpy()

array([[1, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [40]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01 -0.676480  1.148657  1.877875 -1.446105
2013-01-02  0.522061 -0.212003  0.860153 -0.192691
2013-01-03  1.047488 -1.464833 -0.280031 -0.204117
2013-01-04 -0.963258  0.740100  0.946347  0.082516
2013-01-05 -1.505215 -1.029083 -0.884096  0.860888
2013-01-06 -1.031010  0.771898  1.666412 -0.120434

In [41]:
df.sort_values("B")

A         B         C         D
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488
2013-01-02 -0.192691  0.860153 -0.212003  0.522061
2013-01-04  0.082516  0.946347  0.740100 -0.963258
2013-01-06 -0.120434  1.666412  0.771898 -1.031010
2013-01-01 -1.446105  1.877875  1.148657 -0.676480

In [42]:
df.A

2013-01-01   -1.446105
2013-01-02   -0.192691
2013-01-03   -0.204117
2013-01-04    0.082516
2013-01-05    0.860888
2013-01-06   -0.120434
Freq: D, Name: A, dtype: float64

In [43]:
df["A"]

2013-01-01   -1.446105
2013-01-02   -0.192691
2013-01-03   -0.204117
2013-01-04    0.082516
2013-01-05    0.860888
2013-01-06   -0.120434
Freq: D, Name: A, dtype: float64

In [44]:
df[0:3] #iloc 取不到右边

A         B         C         D
2013-01-01 -1.446105  1.877875  1.148657 -0.676480
2013-01-02 -0.192691  0.860153 -0.212003  0.522061
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488

In [45]:
df["20130102":"20130104"] #可以取到右边

A         B         C         D
2013-01-02 -0.192691  0.860153 -0.212003  0.522061
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488
2013-01-04  0.082516  0.946347  0.740100 -0.963258

In [46]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [47]:
df.loc[dates[0]]

A   -1.446105
B    1.877875
C    1.148657
D   -0.676480
Name: 2013-01-01 00:00:00, dtype: float64

In [48]:
df.loc[:, ["A", "B"]]

A         B
2013-01-01 -1.446105  1.877875
2013-01-02 -0.192691  0.860153
2013-01-03 -0.204117 -0.280031
2013-01-04  0.082516  0.946347
2013-01-05  0.860888 -0.884096
2013-01-06 -0.120434  1.666412

In [49]:
df.iat[1,1]

0.8601534504230256

In [50]:
df[df["A"]>0]

A         B         C         D
2013-01-04  0.082516  0.946347  0.740100 -0.963258
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215

In [51]:
df[df>0]

A         B         C         D
2013-01-01       NaN  1.877875  1.148657       NaN
2013-01-02       NaN  0.860153       NaN  0.522061
2013-01-03       NaN       NaN       NaN  1.047488
2013-01-04  0.082516  0.946347  0.740100       NaN
2013-01-05  0.860888       NaN       NaN       NaN
2013-01-06       NaN  1.666412  0.771898       NaN

In [52]:
df2 = df.copy()

In [53]:
df2["E"] = ['one', 'one', 'two', 'three', 'four', 'three']

In [54]:
df2

A         B         C         D      E
2013-01-01 -1.446105  1.877875  1.148657 -0.676480    one
2013-01-02 -0.192691  0.860153 -0.212003  0.522061    one
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488    two
2013-01-04  0.082516  0.946347  0.740100 -0.963258  three
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215   four
2013-01-06 -0.120434  1.666412  0.771898 -1.031010  three

In [55]:
df2[df2["E"].isin(["two", "four"])]

A         B         C         D     E
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488   two
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215  four

In [57]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20130102', periods=6))

In [58]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [59]:
df["F"] = s1

In [60]:
df

A         B         C         D    F
2013-01-01 -1.446105  1.877875  1.148657 -0.676480  NaN
2013-01-02 -0.192691  0.860153 -0.212003  0.522061  1.0
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488  2.0
2013-01-04  0.082516  0.946347  0.740100 -0.963258  3.0
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215  4.0
2013-01-06 -0.120434  1.666412  0.771898 -1.031010  5.0

In [62]:
df.at[dates[0], "A"] = 0

In [64]:
df

A         B         C         D    F
2013-01-01  0.000000  1.877875  1.148657 -0.676480  NaN
2013-01-02 -0.192691  0.860153 -0.212003  0.522061  1.0
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488  2.0
2013-01-04  0.082516  0.946347  0.740100 -0.963258  3.0
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215  4.0
2013-01-06 -0.120434  1.666412  0.771898 -1.031010  5.0

In [65]:
df.iat[0,1] = 0

In [66]:
df

A         B         C         D    F
2013-01-01  0.000000  0.000000  1.148657 -0.676480  NaN
2013-01-02 -0.192691  0.860153 -0.212003  0.522061  1.0
2013-01-03 -0.204117 -0.280031 -1.464833  1.047488  2.0
2013-01-04  0.082516  0.946347  0.740100 -0.963258  3.0
2013-01-05  0.860888 -0.884096 -1.029083 -1.505215  4.0
2013-01-06 -0.120434  1.666412  0.771898 -1.031010  5.0

In [67]:
df.loc[:, "D"] = np.array([5] * len(df))

In [69]:
len(df)

6

In [70]:
df

A         B         C  D    F
2013-01-01  0.000000  0.000000  1.148657  5  NaN
2013-01-02 -0.192691  0.860153 -0.212003  5  1.0
2013-01-03 -0.204117 -0.280031 -1.464833  5  2.0
2013-01-04  0.082516  0.946347  0.740100  5  3.0
2013-01-05  0.860888 -0.884096 -1.029083  5  4.0
2013-01-06 -0.120434  1.666412  0.771898  5  5.0

In [71]:
df2 = df.copy()

In [73]:
df2[df2>0] = -df2

In [74]:
df2

A         B         C  D    F
2013-01-01  0.000000  0.000000 -1.148657 -5  NaN
2013-01-02 -0.192691 -0.860153 -0.212003 -5 -1.0
2013-01-03 -0.204117 -0.280031 -1.464833 -5 -2.0
2013-01-04 -0.082516 -0.946347 -0.740100 -5 -3.0
2013-01-05 -0.860888 -0.884096 -1.029083 -5 -4.0
2013-01-06 -0.120434 -1.666412 -0.771898 -5 -5.0

In [77]:
list(df.columns) + ["E"]

['A', 'B', 'C', 'D', 'F', 'E']

In [78]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])

In [84]:
df1.loc[dates[0:2], "E"] = 1
dates[0:2]

DatetimeIndex(['2013-01-01', '2013-01-02'], dtype='datetime64[ns]', freq='D')

In [85]:
df1

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  1.148657  5  NaN  1.0
2013-01-02 -0.192691  0.860153 -0.212003  5  1.0  1.0
2013-01-03 -0.204117 -0.280031 -1.464833  5  2.0  NaN
2013-01-04  0.082516  0.946347  0.740100  5  3.0  NaN

In [86]:
df1.dropna(how="any")  #数据清理

A         B         C  D    F    E
2013-01-02 -0.192691  0.860153 -0.212003  5  1.0  1.0

In [87]:
df1.fillna(value=5) #数据填充miss值

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  1.148657  5  5.0  1.0
2013-01-02 -0.192691  0.860153 -0.212003  5  1.0  1.0
2013-01-03 -0.204117 -0.280031 -1.464833  5  2.0  5.0
2013-01-04  0.082516  0.946347  0.740100  5  3.0  5.0

In [89]:
df1.isna()

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

In [90]:
df.mean()

A    0.071027
B    0.384798
C   -0.007544
D    5.000000
F    3.000000
dtype: float64

In [91]:
df.mean(1)

2013-01-01    1.537164
2013-01-02    1.291092
2013-01-03    1.010204
2013-01-04    1.953793
2013-01-05    1.589542
2013-01-06    2.463575
Freq: D, dtype: float64

In [92]:
s = pd.Series([1,3,5,np.nan, 6,8], index=dates).shift(2)

In [93]:
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [98]:
df.sub(s, axis=0)

A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -1.204117 -1.280031 -2.464833  4.0  1.0
2013-01-04 -2.917484 -2.053653 -2.259900  2.0  0.0
2013-01-05 -4.139112 -5.884096 -6.029083  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

In [96]:
df

A         B         C  D    F
2013-01-01  0.000000  0.000000  1.148657  5  NaN
2013-01-02 -0.192691  0.860153 -0.212003  5  1.0
2013-01-03 -0.204117 -0.280031 -1.464833  5  2.0
2013-01-04  0.082516  0.946347  0.740100  5  3.0
2013-01-05  0.860888 -0.884096 -1.029083  5  4.0
2013-01-06 -0.120434  1.666412  0.771898  5  5.0

In [99]:
df.apply(np.cumsum)

A         B         C   D     F
2013-01-01  0.000000  0.000000  1.148657   5   NaN
2013-01-02 -0.192691  0.860153  0.936654  10   1.0
2013-01-03 -0.396808  0.580123 -0.528180  15   3.0
2013-01-04 -0.314292  1.526470  0.211921  20   6.0
2013-01-05  0.546596  0.642374 -0.817163  25  10.0
2013-01-06  0.426162  2.308786 -0.045264  30  15.0

In [100]:
df.apply(lambda x: x.max() - x.min())

A    1.065005
B    2.550509
C    2.613490
D    0.000000
F    4.000000
dtype: float64

In [101]:
s = pd.Series(np.random.randint(0, 7, size=10))

In [102]:
s.value_counts()

5    3
1    2
0    2
4    1
3    1
2    1
dtype: int64