# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [109]:
%run initialise.py
import numpy as np

#### 1. Import the numpy package under the name `np` (★☆☆)

In [110]:
import numpy as np

In [111]:
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [112]:
print(np.__version__)
np.show_config()

1.19.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [113]:
answer(2)

print(np.__version__)
np.show_config()


#### 3. Create a null vector of size 10 (★☆☆)

In [114]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [116]:
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [117]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


In [118]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [119]:
Z = np.zeros(10)
Z[4] =1
print(Z[4])

1.0


In [120]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [121]:
answer(7)

Z = np.arange(10,50)
print(Z)


In [122]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [123]:
z = np.arange(10)
z = z[::-1]
print(z)

[9 8 7 6 5 4 3 2 1 0]


In [124]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [125]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [126]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [127]:
Z = np.array([1,2,0,0,4,0])
indice = Z != 0
none_zero = Z[indice]
print(indice)

[ True  True False False  True False]


In [128]:
answer(10)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)


In [129]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [130]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
answer(11)

Z = np.eye(3)
print(Z)


In [132]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [133]:
hint(12)

hint: np.random.random


In [134]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.1513931  0.50488073 0.61741549]
  [0.32469933 0.39835986 0.68136242]
  [0.20350967 0.62703469 0.67841597]]

 [[0.23646308 0.44591499 0.95361566]
  [0.04011561 0.58569451 0.09109092]
  [0.25448728 0.38408846 0.31363189]]

 [[0.79504929 0.8110664  0.39935233]
  [0.6583484  0.32824878 0.0437671 ]
  [0.18272654 0.69277956 0.49885092]]]


In [135]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [136]:
Z = np.random.random((10,10))
min_value = Z.min()
max_value = Z.max()
print(min_value,max_value)

0.002581713285149001 0.9954666414355806


In [137]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [138]:
Z = np.random.random(30)
zmean = Z.mean()
print(zmean)

0.5332239582131061


In [139]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [140]:
hint(15)

hint: array[1:-1, 1:-1]


In [141]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


In [142]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [143]:
hint(16)

hint: np.pad


In [144]:
Z = np.ones((4,4))
Z = np.pad(Z, 1)
print(Z)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [145]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


In [146]:
np.info(np.pad)

 pad(*args, **kwargs)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with

In [147]:
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [148]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [149]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


In [150]:
np.info(np.diag)

 diag(*args, **kwargs)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> 

In [151]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [152]:
Z = np.zeros((8,8))
Z[0:-1:2, 0:-1:2] = 1
Z[1:-1:2, 1:-1:2] = 1
print(Z)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [153]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [154]:
x = int(100 / 56)  + 1
y = int((100 - 56) / 8) + 1

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [155]:
hint(21)
np.info(np.tile)

hint: np.tile
 tile(*args, **kwargs)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat el

In [156]:
Z = np.array([[0,1],[1,0]])
ans = np.tile(Z,(4,4))
print(ans)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [157]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [158]:
hint(22)

hint: (x -mean)/std


In [159]:
Z = np.random.random((5,5))
Z = (Z-Z.mean()) / Z.std()
print(Z.mean())
print(Z)

-1.1546319456101628e-16
[[ 0.92934449  0.02043339  1.74157195 -1.07835706  0.24605565]
 [-0.91708197  0.2266167  -0.23080315 -1.29108514 -1.55592882]
 [ 0.75285162  1.06478633  0.76078815 -1.14358837 -1.76687626]
 [ 1.60028593 -1.38256927  0.07419817  0.39308308  0.96615875]
 [ 1.17096167  0.63506596 -0.27398847 -0.09819072 -0.84373259]]


In [160]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [161]:
hint(23)

hint: np.dtype


In [162]:
answer(23)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


In [163]:
import numpy as np
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)],student) 
print(a['age'])

[21 18]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [164]:
np.dot

<function numpy.dot>

In [165]:
answer(24)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [166]:
Z = np.arange(10)
print(Z>3)
print(Z<8)
print(np.logical_and(Z>3,Z<8))

[False False False False  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True False False]
[False False False False  True  True  True  True False False]


In [167]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [168]:
print(sum(range(5),-3))
print(np.sum(range(5),-1))

7
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [169]:
Z  = np.arange(3)
print(Z)

[0 1 2]


In [170]:
#Z**Z
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z

[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [171]:
print(np.array(0) / np.array(0),
np.array(4) // np.array(2),
np.array([np.nan]).astype(int).astype(float))

nan 2 [-2.14748365e+09]


e:\taskandanswer\python\pytorchenvironment\pytorch\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [172]:
answer(28)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [173]:
hint(29)
answer(29)

hint: np.uniform, np.copysign, np.ceil, np.abs, np.where
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


In [174]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-7.14365052 -8.22048473  8.99110449 -7.3326549   5.1308717   0.72817928
  6.10350403 -5.26919194  1.9470959  -6.06425638]
[-8. -9.  9. -8.  6.  1.  7. -6.  2. -7.]
[-8. -9.  9. -8.  6.  1.  7. -6.  2. -7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [175]:
hint(30)

hint: np.intersect1d


In [176]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


In [177]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [178]:
Z  = np.arange(3)
print(Z)

[0 1 2]


In [179]:
#Z**Z
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z

[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [180]:
print(np.array(0) / np.array(0),
np.array(4) // np.array(2),
np.array([np.nan]).astype(int).astype(float))

nan 2 [-2.14748365e+09]


e:\taskandanswer\python\pytorchenvironment\pytorch\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [181]:
answer(28)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [182]:
hint(29)
answer(29)

hint: np.uniform, np.copysign, np.ceil, np.abs, np.where
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


In [183]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 4.02327279 -3.73011551 -0.30963481  1.70765849 -9.08046871  2.346042
  2.35141931 -8.39092015  7.78853035  9.61880063]
[  5.  -4.  -1.   2. -10.   3.   3.  -9.   8.  10.]
[  5.  -4.  -1.   2. -10.   3.   3.  -9.   8.  10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [184]:
hint(30)

hint: np.intersect1d


In [185]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


In [186]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 4 5 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [187]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [188]:
Z = np.zeros(1) / 0
print(Z)

e:\taskandanswer\python\pytorchenvironment\pytorch\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


[nan]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [189]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


In [190]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z.dtype)

[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])]


e:\taskandanswer\python\pytorchenvironment\pytorch\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [191]:
Z = np.random.random((10,2))
print(Z)
point = np.array([1,2])
distance  = (Z - point)[:,0]**2 + (Z-point)[:,1]**2
index = distance.argmin()
Find_points = Z[index,:]
print(Find_points)

[[0.52425556 0.00418913]
 [0.4812765  0.43566472]
 [0.08683915 0.44111109]
 [0.69940512 0.09552505]
 [0.53055508 0.84067133]
 [0.92382976 0.27112663]
 [0.04984381 0.15655837]
 [0.94848875 0.37384471]
 [0.9351102  0.62650315]
 [0.89944032 0.09869365]]
[0.53055508 0.84067133]


In [192]:
answer(52)

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


In [193]:
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.24732524 0.46968594 0.74268095 0.25856684 0.14759959
  0.71090175 0.22427346 0.49654778 0.26849287]
 [0.24732524 0.         0.71238138 0.71093731 0.13291823 0.19118636
  0.7112932  0.17799278 0.46942977 0.4975525 ]
 [0.46968594 0.71238138 0.         0.90113972 0.67968948 0.55012364
  0.82579136 0.61920931 0.724599   0.33503587]
 [0.74268095 0.71093731 0.90113972 0.         0.57962767 0.6089154
  0.09494074 0.55724976 0.24949424 0.95820297]
 [0.25856684 0.13291823 0.67968948 0.57962767 0.         0.13037477
  0.57837885 0.06671986 0.3366067  0.52705844]
 [0.14759959 0.19118636 0.55012364 0.6089154  0.13037477 0.
  0.58701157 0.07942282 0.35978107 0.41035165]
 [0.71090175 0.7112932  0.82579136 0.09494074 0.57837885 0.58701157
  0.         0.54581581 0.24229984 0.90861784]
 [0.22427346 0.17799278 0.61920931 0.55724976 0.06671986 0.07942282
  0.54581581 0.         0.30863123 0.4894292 ]
 [0.49654778 0.46942977 0.724599   0.24949424 0.3366067  0.35978107
  0.24229984 0.308631

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [194]:
hint(53)

hint: view and [:] =


In [195]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


In [196]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[11.772928 55.543842 50.168453 78.14973  67.059586 76.53486  53.1717
 21.418837 51.809887 29.305164]
[11 55 50 78 67 76 53 21 51 29]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [197]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


In [198]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]



#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [199]:
answer(55)

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


In [200]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [201]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


In [202]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X + Y*Y)
print(X.shape,Y.shape)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

(10, 10) (10, 10)
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [203]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


In [204]:
n=10
p=3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n),p,replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [205]:
answer(58)

# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


In [206]:
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


#### 59. How to sort an array by the nth column? (★★☆)

In [207]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


In [208]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 4 2]
 [0 0 9]
 [7 6 3]]
[[0 0 9]
 [0 4 2]
 [7 6 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [209]:
answer(60)

# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


In [210]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print(Z.any(axis=0))
print(z)
print((~Z.any(axis=0)).any())

[[2 0 1 1 2 1 1 0 2 1]
 [1 0 2 2 1 2 1 2 1 2]
 [0 0 2 1 0 2 1 2 1 1]]
[ True False  True  True  True  True  True  True  True  True]
[9 8 7 6 5 4 3 2 1 0]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [211]:
answer(61)

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


In [212]:
Z = np.random.uniform(0,1,(10,10))
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[[0.63307353 0.97703554 0.58288656 0.02908639 0.281277   0.18289699
  0.54558527 0.30438143 0.86149095 0.09543871]
 [0.13956943 0.72627496 0.34997624 0.41516076 0.96966585 0.7755594
  0.07825588 0.99225418 0.61674725 0.48895989]
 [0.76710492 0.62987746 0.85928274 0.06286993 0.80283435 0.11094892
  0.68984787 0.71661603 0.71233505 0.77655565]
 [0.83866434 0.24607925 0.99284618 0.84136834 0.98316421 0.83090065
  0.52555249 0.69194631 0.88101531 0.56756428]
 [0.34431401 0.87046224 0.83569619 0.53009172 0.71101016 0.42120912
  0.86088908 0.16373111 0.54702689 0.35381722]
 [0.6648087  0.04375488 0.39903552 0.32179139 0.2206495  0.62170006
  0.44710762 0.13467352 0.89032736 0.85831813]
 [0.18533289 0.93194422 0.86983212 0.37740859 0.97102148 0.87465415
  0.50724762 0.59772977 0.31246041 0.67578899]
 [0.34845397 0.81379819 0.87222645 0.75031198 0.09650316 0.03822337
  0.19340765 0.25550993 0.79514245 0.33231733]
 [0.89656589 0.51285192 0.07159302 0.44557287 0.75821233 0.33316294
  0.29404116 

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [215]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


In [217]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])

for x,y,z in it: 
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [218]:
answer(63)

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


In [219]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [220]:
answer(64)

# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


In [222]:
#np.add.at?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [221]:
answer(65)

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


In [227]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X) # X mean weight
print(F)
#np.bincount?

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [228]:
answer(66)

# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))


In [232]:
#np.unique?
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
print(I)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I), n)

[[[1 0 1]
  [0 0 1]
  [1 1 0]
  [0 0 0]
  [1 1 0]
  [0 0 1]
  [1 1 1]
  [1 1 0]
  [1 0 1]
  [0 1 0]
  [0 1 0]
  [0 1 0]
  [0 0 1]
  [1 1 1]
  [0 1 1]
  [0 0 0]]

 [[1 1 0]
  [1 0 1]
  [0 1 0]
  [0 1 0]
  [1 0 1]
  [0 0 0]
  [0 1 1]
  [0 0 1]
  [0 1 0]
  [1 1 0]
  [0 0 1]
  [0 1 1]
  [1 1 1]
  [1 1 0]
  [1 0 1]
  [1 1 0]]

 [[0 1 0]
  [0 0 0]
  [0 1 0]
  [1 0 1]
  [0 0 1]
  [0 1 1]
  [0 1 1]
  [1 0 0]
  [1 0 1]
  [0 1 0]
  [1 0 1]
  [1 1 0]
  [0 0 0]
  [0 0 1]
  [1 0 0]
  [1 0 0]]

 [[1 0 0]
  [1 1 0]
  [0 1 0]
  [0 1 1]
  [0 1 0]
  [1 1 1]
  [0 1 1]
  [1 1 1]
  [0 0 1]
  [0 0 1]
  [1 0 0]
  [1 1 0]
  [0 0 1]
  [0 0 1]
  [1 0 0]
  [1 1 0]]

 [[0 1 0]
  [0 1 0]
  [0 1 0]
  [1 0 1]
  [1 0 1]
  [0 1 1]
  [0 1 1]
  [1 1 1]
  [1 1 1]
  [0 0 0]
  [1 1 1]
  [0 1 0]
  [1 1 0]
  [0 0 1]
  [1 0 0]
  [0 1 0]]

 [[0 1 0]
  [1 0 1]
  [0 1 1]
  [1 1 0]
  [1 0 0]
  [1 1 1]
  [0 1 1]
  [0 1 1]
  [1 0 1]
  [1 0 1]
  [0 0 0]
  [0 1 1]
  [1 1 0]
  [0 0 1]
  [1 0 0]
  [0 1 1]]

 [[0 1 1]
  [0 1 0]
  [1 1 1

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [233]:
answer(67)

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


In [234]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)


[[46 67 61 51]
 [64 41 42 57]
 [38 65 58 31]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [235]:
answer(68)

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


In [253]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
#rint(D)
S = np.random.randint(0,10,100)

print(S)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S))
print(pd.Series(D).groupby(S).mean())

[8 7 8 1 7 7 8 2 7 3 1 2 1 2 6 5 0 9 9 1 1 3 4 7 2 0 8 8 8 8 5 6 6 5 9 7 6
 7 8 1 7 0 4 7 7 0 0 2 2 2 4 8 7 0 9 0 8 9 2 3 5 9 2 0 4 5 9 0 3 9 5 6 5 9
 2 4 8 6 7 8 1 1 4 5 6 6 5 4 2 0 1 2 3 9 6 1 2 2 2 4]
[0.2544861  0.5261195  0.61237244 0.46035541 0.47478893 0.49295354
 0.46766298 0.56994017 0.45082032 0.45250487]
0    0.254486
1    0.526120
2    0.612372
3    0.460355
4    0.474789
5    0.492954
6    0.467663
7    0.569940
8    0.450820
9    0.452505
dtype: float64


In [257]:
ser = pd.Series([390., 350., 30., 20.],
                index=['Falcon', 'Falcon', 'Parrot', 'Parrot'], name="Max Speed")

print(ser.groupby([1,2,1,2]).mean())

1    210.0
2    185.0
Name: Max Speed, dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [242]:
answer(69)

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


In [250]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
print(np.diag(np.dot(A, B)))

# Fast version
print(np.sum(A * B.T, axis=1))
print((A@B.T) == (np.dot(A, B.T)))

# Faster version
print(np.einsum("ij,ji->i", A, B))

[1.78661897 1.13661442 1.06150506 1.95371222 1.02617815]
[1.78661897 1.13661442 1.06150506 1.95371222 1.02617815]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[1.78661897 1.13661442 1.06150506 1.95371222 1.02617815]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)